# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://ivisdun.github.io"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: YUTONG DUN-Portfolio
# Description of the Site
description: Interior, Architectural and Spatial Design
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ivisdun@gmail.com
instagram_username: dyt0117
linkedin_username: yutong dun


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: YUTONG DUN
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
education: 
  - BA Environmental Design - Beijing Forestry University
  - MA Interior, Architecture and Spatial Design - University of Edinburgh
author-about: An interior and spatial designer with a strong interest in adaptive reuse and the emotional connection between people and space. My design practice focuses on transforming existing structures and forgotten urban sites into spaces that evoke memory,interaction, and inclusivity. I value material honesty, sensory experience, and sustainable design approaches that respect both the past and the environment.
author-url: "https://ivisdun.github.io"
location: "SHENZHEN, CHINA"

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/









